# Site settings
title: "MYWords"
description: >

author: UV
url: "https://youweiMa.github.io" # the base hostname & protocol for your site

google_analytics_id:
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

